<?php

/**
 * Test class for TournamentException.
 * Generated by PHPUnit on 2012-05-18 at 19:19:10.
 * @group tournament
 */
class TournamentExceptionTest extends PHPUnit_Framework_TestCase {

    protected function setUp() {
        TournamentException::init();
    }

    public function test__construct() {
        $rf = new ReflectionClass('TournamentException');
        $constants = $rf->getConstants();
        foreach ($constants as $constant) {
            $exception = new TournamentException($constant);
            parent::assertEquals($exception->getCode(), $constant);
        }
    }


}

?>