<?php

/**
 * Test class for TournamentGroup.
 * Generated by PHPUnit on 2012-05-16 at 17:04:01.
 * @group tournament
 */
class TournamentGroupTest extends PHPUnit_Framework_TestCase {

    /** @var TournamentGroup */
    private $group;

    protected function setUp() {
        $this->group = new TournamentGroup();
    }

    public function testGetTeams() {
        parent::assertEquals(array(), $this->group->getTeams());
        $this->group->addTeam('hello');
        parent::assertEquals(array('hello'), $this->group->getTeams());
    }

    public function testGetTeamCount() {
        parent::assertEquals(0, $this->group->getTeamCount());
        $this->group->addTeam('hello');
        parent::assertEquals(1, $this->group->getTeamCount());
    }

    public function testAddTeam() {
        $invalid = array('', array(), new Exception(), null, 0);
        foreach ($invalid as $value) {
            $this->group->addTeam($value);
            parent::assertEquals(0, $this->group->getTeamCount());
        }
    }

}

?>