<?php

/**
 * Test class for PlayoffTreePrintout.
 * Generated by PHPUnit on 2012-02-01 at 11:48:24.
 * @group playoff
 */
class PlayoffTreePrintoutTest extends PHPUnit_Framework_TestCase {

    public function test__construct() {
        $generator = PlayoffGenerator::create(array('A', 'B', 'C', 'D'));
        $tree = new PlayoffTree($generator);
        parent::assertInstanceOf('PlayoffTreePrintout', new PlayoffTreePrintout($tree));
        parent::assertInstanceOf('PlayoffTreePrintout', new PlayoffTreePrintout($tree, true));
        
        $invalid_values = array('a', null, false, array(), new Exception());
        foreach ($invalid_values as $value) {
            $this->invalid_arguments($value);
        }
    }

    private function invalid_arguments($argument) {
        try {
            new PlayoffTreePrintout($argument);
            parent::fail('This test did not fail as expected');
        } catch (PlayoffException $e) {
            parent::assertEquals($e->getCode(), PlayoffException::EXC5);
        }
    }
}

?>
