<?php

/**
 * Test class for PlayoffException.
 * Generated by PHPUnit on 2012-02-01 at 11:09:00.
 * @group playoff
 */
class PlayoffExceptionTest extends PHPUnit_Framework_TestCase {

    protected function setUp() {
        PlayoffException::init();
    }

    public function test__construct() {
        $rf = new ReflectionClass('PlayoffException');
        $constants = $rf->getConstants();
        foreach ($constants as $constant) {
            $exception = new PlayoffException($constant);
            parent::assertEquals($exception->getCode(), $constant);
        }
    }

}

?>
