<?php
/*
 * This file is part of the PHP Sports Generators (https://bitbucket.org/zdenekdrahos/php-sports-generators)
 * Copyright (c) 2012, 2013 Zdenek Drahos (https://bitbucket.org/zdenekdrahos)
 * PHP Sports Generators is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License 3, or any later version
 * For the full license information view the file license.txt, or <http://www.gnu.org/licenses/>.
 */

/**
 * SeasonPrintout class
 * - for displaying season schedule, which was generated by SeasonGenerator
 */
class SeasonPrintout {
    
    /** @var SeasonSchedule */
    private $schedule;

    /**
     * @param SeasonSchedule $seasonSchedule
     * @throws SeasonException 
     */
    public function __construct($seasonSchedule) {
        if (!($seasonSchedule instanceof SeasonSchedule)) {
            throw new SeasonException(SeasonException::EXC4);
        }
        $this->schedule = $seasonSchedule;
    }
    
    public function printLines() {        
        for ($p = 1; $p <= $this->schedule->periodCount; $p++) {
            echo '<hr />' . $p . '.period<br />';
            foreach ($this->schedule->rounds as $number => $round) {
                echo ($this->schedule->getNumberOfRoundsInPeriod() * ($p - 1) + $number) . '.round<br />';
                foreach ($round as $match) {
                    echo $match->home . ' : ' . $match->away . '<br />';
                    $match->swapTeams();
                }
            }
        }
    }    
    
    public function printTable() { 
        echo '<table style="width:100%;text-align:center">';
        for ($p = 1; $p <= $this->schedule->periodCount; $p++) {
            echo '<tr><th colspan="3"><em>' . $p . '.period</em></th></tr>';
            foreach ($this->schedule->rounds as $number => $round) {
                $roundNumber = $this->schedule->getNumberOfRoundsInPeriod() * ($p - 1) + $number;
                echo '<tr><th colspan="3">' . $roundNumber . '.round</th></tr>';
                foreach ($round as $match) {
                    echo '<tr>';
                    echo '<td>' . $match->home . '</td>';
                    echo '<td><strong>:</strong></td>';
                    echo '<td>' . $match->away . '</td>';                    
                    echo '</tr>';
                    $match->swapTeams();
                }
            }
        }
        echo '</table>';
    }   

}

?>
