<?php

/**
 * Test class for Functions.
 * Generated by PHPUnit on 2012-02-01 at 11:33:29.
 * @group playoff
 */
class FunctionsTest extends PHPUnit_Framework_TestCase {
    
    public function testIs_power_of_two() {        
        for ($i = 2; $i < 1024; $i*=2) {
            parent::assertTrue(Functions::is_power_of_two($i));
        }
        
        parent::assertFalse(Functions::is_power_of_two(7));
        parent::assertFalse(Functions::is_power_of_two(1023));
        for ($i = -10; $i <= 1; $i++) {            
            parent::assertFalse(Functions::is_power_of_two($i));
        }        
        // only int
        parent::assertFalse(Functions::is_power_of_two(7.5));
        parent::assertFalse(Functions::is_power_of_two(null));
    }

}

?>
