<?php

/**
 * Test class for SeasonMatch.
 * Generated by PHPUnit on 2012-02-01 at 13:09:49.
 * @group season
 */
class SeasonMatchTest extends PHPUnit_Framework_TestCase {

    private $home;
    private $away;
    /** @var SeasonMatch */
    protected $object;

    protected function setUp() {
        $this->home = 1;
        $this->away = 2;
        $this->object = new SeasonMatch($this->home, $this->away);
    }

    public function test__construct() {
        parent::assertInstanceOf('SeasonMatch', $this->object);        
        $this->invalid_arguments($this->home, null);
        $this->invalid_arguments(null, $this->away);
        $this->invalid_arguments(null, null);
    }
    
    public function testSwapTeams() {
        $this->assertTeams($this->home, $this->away);
        $this->object->swapTeams();
        $this->assertTeams($this->away, $this->home);
    }
    
    private function assertTeams($home, $away) {
        parent::assertEquals($this->object->home, $home);
        parent::assertEquals($this->object->away, $away);
    }
    
    private function invalid_arguments($home, $away) {
        try {
            new SeasonMatch($home, $away);
            parent::fail('This test did not fail as expected');
        } catch (SeasonException $e) {
            parent::assertEquals($e->getCode(), SeasonException::EXC3);
        }
    }

}

?>
