<?php

/**
 * Test class for SeasonException.
 * Generated by PHPUnit on 2012-02-01 at 13:07:34.
 * @group season
 */
class SeasonExceptionTest extends PHPUnit_Framework_TestCase {

    protected function setUp() {
        SeasonException::init();
    }

    public function test__construct() {
        $rf = new ReflectionClass('SeasonException');
        $constants = $rf->getConstants();
        foreach ($constants as $constant) {
            $exception = new SeasonException($constant);
            parent::assertEquals($exception->getCode(), $constant);
        }
    }
}

?>
