<?php

/**
 * Test class for SeasonPrintout.
 * Generated by PHPUnit on 2012-02-01 at 13:25:05.
 * @group season
 */
class SeasonPrintoutTest extends PHPUnit_Framework_TestCase {

    public function test__construct() {
        $generator = SeasonGenerator::create(array('A', 'B', 'C', 'D'), 2);        
        $generator->generate();
        parent::assertInstanceOf('SeasonPrintout', new SeasonPrintout($generator->getSchedule()));
        
        $invalid_values = array('a', null, false, array(), new Exception());
        foreach ($invalid_values as $value) {
            $this->invalid_arguments($value);
        }
    }

    private function invalid_arguments($argument) {
        try {
            new SeasonPrintout($argument);
            parent::fail('This test did not fail as expected');
        } catch (SeasonException $e) {
            parent::assertEquals($e->getCode(), SeasonException::EXC4);
        }
    }

}

?>
